steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/cloudbuuld/nodeapp.git']
# build the container image
- name: 'asia-south1-docker.pkg.dev/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/cloud-buildpoc/cicd/:$COMMIT_SHA', '.']

# push the container image to Container Registry
- name: 'asia-south1-docker.pkg.dev/cloud-builders/docker/gcloud'
  args: ['push', 'asia-south1-docker.pkg.dev/cloud-buildpoc/cicd:$COMMIT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY
