steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/cloudbuuld/nodeapp.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloudbuild-poc-433710/github.com/cloudbuuld/nodeapp:$COMMIT_SHA \ '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cloudbuild-poc-433710/github.com/cloudbuuld/nodeapp:$COMMIT_SHA']

substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: cloudbuild-poc-433710
    _ZONE: asia-south1
options:
  logging: GCS_ONLY
  logsBucket: gs://node-logs-bucket/
 
