steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/cloudbuuld/nodeapp.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/cloudbuild-poc-433710/my-cloud-build/nodeapp', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/cloudbuild-poc-433710/my-cloud-build/nodeapp']

substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: cloudbuild-poc-433710
    _ZONE: us-east1 
options:
  logging: GCS_ONLY
  logsBucket: gs://node-logs-bucket/
